# Generated by Django 3.0.3 on 2020-03-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200303_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_type',
            field=models.CharField(default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='generic room', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='generic', max_length=50),
        ),
    ]
